name: fault-profile-tool
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy >= 1.18.1
  - matplotlib >= 3.1.1
  - netcdf4 >= 1.4.2
  - ipython >= 7.9.0
  - scipy >= 1.3.1
  - rasterio >= 1.1.0
  - geopandas >= 0.6.1
  - pyqt == 5.9.7
  - jupyterlab >= 3.0.9
  - pip
